### ISSUE TITLE
Not specifying all grouped options leaves the unspecified ones undefined

### ISSUE THREAD

**Issue by reclaimingmytime** [loebi-ch/jquery-clock-timepicker#12]
When setting only part of a grouped option, the unspecified options are undefined.

For example, for the "i18n" group, the available options are "cancelButton" and "okButton."
This code shows the "Abort" text as expected:
`i18n: {
   cancelButton: 'Abort',
   okButton: 'OK'
}`

However, this code leaves the "OK" button empty:
`i18n: {
   cancelButton: 'Abort'
}`
Rendering the following HTML:
`<div style="text-align: right; padding: 15px 30px;"><a style="text-decoration:none; color:#0797FF; font-family:Arial; font-size:20px; padding-left:30px">Abort</a><a style="text-decoration:none; color:#0797FF; font-family:Arial; font-size:20px; padding-left:30px"></a></div>`

The same goes for any unspecified option that is part of a group, e.g. fonts and colors.

The current workaround I could find is to specify all available options.

**Comment by loebi-ch** [comment]
Thank you for reporting this issue. I fixed it in version 2.2.2.

**Comment by reclaimingmytime** [comment]
Thank you
