### ISSUE TITLE
Minimum does not work with non hour-values

### ISSUE THREAD

**Issue by robertUzias** [loebi-ch/jquery-clock-timepicker#15]
Hello. Basically when I set a minimum value of, for example: 15:48, the clock bugs and the "15" in the clock dissapears, but it's still clickable.

[proof](https://i.imgur.com/JSfQz5a.png)

` $('.standard').clockTimePicker({
		minimum:'15:48', 
		maximum:'20:00'
  });`

The '15' should still appear. Could you help me in this one? Thanks...

**Comment by loebi-ch** [comment]
Problem solved with version 2.3.0
