### ISSUE TITLE
Feature request: use data attribute of DOM element to pass options on initialize

### ISSUE THREAD

**Issue by sabat24** [loebi-ch/jquery-clock-timepicker#18]
In my project, I use multiple instances of this picker to allow users to choose the hours of serving ordered catering options. Most of main timepicker options are common, but some fields have got different min, max restrictions. This is why I added some data attributes to my DOM element when I generated it from PHP as this is the easiest way to provide some different options for different instances.

I added following code in constructor at the end of INITIALIZE VARIABLES section.

```
var dataOptions = {}, _data = element.data(), _key;
for (var i in _data) {
	if (i.indexOf('_ctpicker') === 0) {
		_key = i.replace('_ctpicker', '');
		_key = _key.charAt(0).toLowerCase() + _key.substr(1);
		dataOptions[_key] = _data[i];
	}
}

settings = $.extend(settings, dataOptions);
```

I can use right now following code

`<input data-_ctpicker-minimum="10:00" />`

to set minimum option.

However validation and filtering are omitted because they are earlier in code in global section between: 63 and 92 lines.

You can create a private method to filter and validate options and call it right after data attributes are parsed.

**Comment by loebi-ch** [comment]
I implemented this in version 2.3.0.

Please see documentation (or code) of how I did it...

Thanx again for all your precious inputs with detailed recommendation and solution proposals.
