### ISSUE TITLE
Issue hours with precision 5

### ISSUE THREAD

**Issue by kynosoft** [loebi-ch/jquery-clock-timepicker#23]
Hi, we use the timepicker with a precision of 5. When it is 09:58 (or 09:59), the time is rounded to 09:00 instead of 10:00. What can we do to solve this? With regards Kynosoft

**Comment by kynosoft** [comment]
Version used is 2.3.1

**Comment by loebi-ch** [comment]
To fix this issue you have to replace the Code on line 1223:

`if (min >= 60) min = 0;`

through

`if (min == 60) {  
  min = 0;  
  hour++;  
  if (hour == 24 && !settings.duration) hour = 0;  
}`

This is not tested. I try to find some time soon to test it and make a new release...

**Comment by loebi-ch** [comment]
Fixed with version 2.3.2
