### ISSUE TITLE
show always hours picker as first picker

### ISSUE THREAD

**Issue by despokd** [loebi-ch/jquery-clock-timepicker#25]
I want to display the hours picker first when i click on the input field. Even then the user click on the minutes in the input field. The minute picker would be shown after setting the hours.

**Is there a way to code it by myself or can you add an option for it?**

**Comment by loebi-ch** [comment]
Actually it has been like that in previous versions, but my use case forced me to be able to select minutes on first click. Unfortunately I haven't implemented it with an option.

Right now, I don't find the time to implement it, but it would go as follows:

Between lines 14 + 15, insert a new option `alwaysSelectHoursFirst: false`and then replace the following code on line 543

`if (event.offsetX >= inputElementCenter - 2) {`

trough:

`if (event.offsetX >= inputElementCenter - 2 && (popupVisible || !settings.alwaysSelectHoursFirst)) {`

Then set this option (`alwaysSelectHoursFirst`) to true.

Not tested, but it should work...

**Comment by loebi-ch** [comment]
Fixed with version 2.3.2
