### ISSUE TITLE
onlyShowClockOnDesktop like onlyShowClockOnMobile

### ISSUE THREAD

**Issue by gbaster** [loebi-ch/jquery-clock-timepicker#26]
Hi,
I ll like the clock to displayed only on Desktop sites because it has some issues on mobile
Can you help me to add this feature too?
thank you
George

**Comment by loebi-ch** [comment]
Sorry @gbaster for my late reply.
I'm not willing to implement this feature, please name the issues that is has on mobiles and we try to fix these. Otherwise you have to churn the code by yourself and try to find your own solution what you've maybe done in the meantime...
