### ISSUE TITLE
Invalid DNS name on linked demo

### ISSUE THREAD

**Issue by reclaimingmytime** [loebi-ch/jquery-clock-timepicker#27]
When following the link "See a demo here" in the [readme](https://github.com/loebi-ch/jquery-clock-timepicker/blob/master/README.md) (currently https://plugins.slyweb.ch/jquery-clock-timepicker/), the following certificate error gets displayed:

> **This site is missing a valid, trusted certificate (net::ERR_CERT_COMMON_NAME_INVALID).**

This indicates the SSL certificate has not been issued properly for the subdomain plugins.slyweb.ch.

**Comment by loebi-ch** [comment]
Thank you for the reminder. Unfortunately the renewal process for the SSL Certificate does not work automatically yet. I will fix it tomorrow.

**Comment by reclaimingmytime** [comment]
Thank you.
