### ISSUE TITLE
[Mobile]. Hour/Minute doesn't selected with single 'touch' to a value

### ISSUE THREAD

**Issue by Yauheni-Butski** [loebi-ch/jquery-clock-timepicker#28]
I founded that I can't select value with single 'touch'. For 'Hours' mode picker just leave 'hour' value as '00' and change mode to 'Minutes'. But all works fine when I hold my finger and move it ('touchmove').

So, I founded that  function 'processTimeSelection' depends on 'isDragging' value. But this value is set to 'true' only after calling 'processTimeSelection'. 

So, I fixed it with simple replacing initialization before calling function. 
I don't no, should you fix it ot it is desired behavior for mobile version, so I will just leave it here.
![jquery-clock-timepicker](https://user-images.githubusercontent.com/11922029/70913412-0355f600-2027-11ea-94af-9ef1b9cf1029.png)

**Comment by loebi-ch** [comment]
Going to implement this in the new version. As soon as issue #14 is clear I'm going to release the new version.

**Comment by loebi-ch** [comment]
Resolved in version 2.3.3
