### ISSUE TITLE
Auto-close picker

### ISSUE THREAD

**Issue by Polm90** [loebi-ch/jquery-clock-timepicker#33]
If I open the picker and then I select only the hour (or neither it...) and then I click somewhere outside the picker (maybe on another input, or a submit button...) the picker doesn't close but remains visible... It would be useful to have an autoclose option... (maybe I didn't find it...)
Thank you

**Comment by loebi-ch** [comment]
Hi @Polm90 

I've tested this on the example page (https://plugins.slyweb.ch/jquery-clock-timepicker) and this seems to work. The picker automatically closes if I click somewhere else...

Can you please provide me with more information?
What browser, what device? Can you find any error in the developer tools console?

Best regards

**Comment by Polm90** [comment]
Sorry, it was my fault....
I had a stopPropagation on the onclick event which i had forgotten... I had removed it and now the picker closes properly :)
