### ISSUE TITLE
Add time

### ISSUE THREAD

**Issue by evandropolizei** [loebi-ch/jquery-clock-timepicker#38]
Hello,

I have 2 input where the first will receive the start time and the second the end time, but I would like the end time to be added 15 minutes based on the start time, example, start time 08:00 end time 08:15, that automatically.

thanks in advance

Evandro Polizei

**Comment by loebi-ch** [comment]
Hello @evandropolizei 

You can use the function ```$('#time1').clockTimePicker('value', newValue)``` to set a value of a clock timepicker element programmatically. Furthermore you'll find ```onAdjust``` in the clock timepicker's configuration object that you can use to set a function to react upon a change to a clock timepicker element.

In the end it's quite simple:
When one clock time picker's value is changing, then add 15 minutes to the current time and set it on the second clock time picker element.
When the second clock time picker's value is changing, then subtract 15 minutes to the current time and set it on the first clock time picker element.

Here is an example:

```
<html>
 <head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <title>jQuery Clock Time Picker Example</title>
  <script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
  <script type="text/javascript" src="jquery-clock-timepicker.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
	  $('#time1').clockTimePicker({
		onAdjust: (newVal, oldVal) => {
			$('#time2').clockTimePicker('value', calcTime(newVal, 15));
		}
	  });
	  $('#time2').clockTimePicker({
		onAdjust: (newVal, oldVal) => {
			$('#time1').clockTimePicker('value', calcTime(newVal, -15));
		}
	  });
	  $('#time1').clockTimePicker('value', '10:00');
	});
	function calcTime(time, minutesToAdd) {
		if (time.match(/^([0-9]+):([0-9]+)$/)) {
			let mins = parseInt(RegExp.$1) * 60 + parseInt(RegExp.$2);
			mins += minutesToAdd;
			const hours = Math.floor(mins / 60);
			mins = mins - hours * 60;
			return (hours < 10 ? '0' : '') + hours + ':' + (mins < 10 ? '0' : '') + mins;
		}
		return time;
	}
  </script>
 </head>
 <body>
  <input id="time1" type="text" value="08:00" />
  <input id="time2" type="text" value="08:15" />
 </body>
</html>
```

Please make sure to use the newest version 2.5.0 of jquery.clock-timepicker!
