### ISSUE TITLE
Overwrite element's width

### ISSUE THREAD

**Issue by Erando89** [loebi-ch/jquery-clock-timepicker#4]
Hi there, and thanks for that lib!
When I'm using it though it keeps setting the style, e.g.:
before init: `<input type="time" />`
after init: `<input type="time" style="width: 58px; caret-color: white;" />`

How do I prevent this from happening? I'm missing a `style` option. Using the `autosize` option didn't change anything.

Cheers

**Comment by loebi-ch** [comment]
Hi!

The autosize option is by default true. Have you tried to set it to false? Is "width" always automatically set? Right now I cannot check it, but I will have a look soon.
It should be possible to set other styles directly to your element...

Best regards,
Andy

**Comment by Erando89** [comment]
Hi Andy,

thanks for replying. You're right, setting `autosize` to `false` does indeed avoid the element's `width` style attribute. Thank you.

Cheers
