### ISSUE TITLE
Ability to also set seconds

### ISSUE THREAD

**Issue by xztraz** [loebi-ch/jquery-clock-timepicker#40]
Pretty timepicker!
an option to enable also selecting seconds would be awesome. just copy minutes page for layout. some backend stuff needed for that tho

**Comment by loebi-ch** [comment]
Hi @xztraz!

The possible use cases for this seem to me very rare and I can only say that I won't develop this.
But whoever needs this, feel free to extend the code. 😆

Best regards
Andy

**Comment by xztraz** [comment]
there are no good time pickers with an option for seconds and that's something we're looking for a live broadcast/scene planning tool where everything is planned down to the second. (open source of course). but we could use this as a base and make our own for our needs if there is no other use cases for it.  

Br
