### ISSUE TITLE
Problem with Bootstrap 3.4.1.

### ISSUE THREAD

**Issue by veolys-nanne** [loebi-ch/jquery-clock-timepicker#47]
Hi!
Our customers are very satisfied with the ClockTimerPicker.
We are on an old project with Bootsrap 3.4.1.
As Bootstrap's modal uses transform css, widget's fixed position doesn't work.
Here is a jsfiddle : https://jsfiddle.net/f4gs6vde/
We found a workaround by overriding the modal's transform behavior.

But fixed position is maybe not the most robust solution.

**Comment by loebi-ch** [comment]
Hi @veolys-nanne!

Thank you for the report. I agree with you that fixed position is maybe not the perfect solution.
I don't remember why I solved it that way.

You could insert in CSS the following code:

```
.clock-timepicker .clock-timepicker-popup {
  position: absolute !important;
  left: auto !important;
  top: auto !important;
}
```

This makes the clock timepicker's popup position absolute while ignoring the set left and top properties.

Before implementing this generally in my code, I must do some checks first.

Best regards,
Andy

**Comment by loebi-ch** [comment]
Hey @veolys-nanne 

I've just rembered why I solved it with fixed position.

Depending on the element's location in the viewport, I can position the clock timepicker's dialog above the input field:

![image](https://user-images.githubusercontent.com/28792333/198261851-b311e1b3-e221-4382-8958-175c1762d5c6.png)

This would also be possible with absolute positioning, but needs some more effort on my side to implement. But you're right, absolute positioning would generally be a better solution than fixed positioning. I noted it down on my todo list, but cannot tell you when I'll find the time to tackle it...

**Comment by loebi-ch** [comment]
Sometimes it's useful to have a changelog:

Version 2.4.0
- **Position popup "fixed" instead of "absolute" to prevent popup from cut-off in containers with overflow: hidden.**  

So I don't see another solution than fixed positioning.
I will leave it as it is... use your's or above's workaround to use the clock timerpicker with Bootstrap's modal dialog!

**Comment by veolys-nanne** [comment]
@loebi-ch
JQueryUI-Datepicker adds the widget to the root of the body and use absolute position.
It could be a solution to prevent cut-off too and conflict between fixed and transform css.

Thanks for your workaround.
