### ISSUE TITLE
onOpen: Get original input

### ISSUE THREAD

**Issue by Erando89** [loebi-ch/jquery-clock-timepicker#5]
Hi Andy,

sorry to bother you again. I make use of the `onOpen` option:

```
var clockTimePickerOptions = {
    precision: 15,
    onOpen : handleClockTimePickerOpenEvent,
    autosize: false
};
function initClockTimePickerPlugin() {
    $('.clockTime').clockTimePicker(clockTimePickerOptions);
}
function handleClockTimePickerOpenEvent() {
    console.log($(this));
}
```

I would expect `$(this)` to return the `input` which triggered the plugin in the first place. How do I access that `input`?

Best regards

Erando

**Comment by loebi-ch** [comment]
Hi Erando

Why don't you use an anonymous function like this:

```
$('.clockTime').each(function() {  
    var element = $(this);
    element.clockTimePicker({  
        precision: 15,  
        onOpen: function() {  
            //now you can access element...
            console.log(element);  
        }  
    });  
});
```

I leave this issue marked as opened. In the next update, I'm going to pass the element to the onOpen function, but for now, you can work as described above.

Btw: In version 2.1.0 I changed the default for autosize from true to false, so you don't need to specify `autosize: false` anymore.

Best regards
Andy

**Comment by loebi-ch** [comment]
I'm now calling the event functions (callbacks) with call() passing the element's context, so that you can access the element as you stated with $(this).
Your code should work as soon as you updated to version 2.1.2.

**Comment by Erando89** [comment]
Great, thank you!
