### ISSUE TITLE
when precision is 60, does it possiable not switch to minute mode?

### ISSUE THREAD

**Issue by wzshuang** [loebi-ch/jquery-clock-timepicker#8]
when precision is 60, the minute is unable to change, but after I input in the hour field, the clock changed to minute mode, I think close panel is more friendly.

**Comment by loebi-ch** [comment]
You're absolutely right. Of course it should not switch to minute mode when precision is 60. That was a bug and is now corrected in version 2.1.5.

**Comment by wzshuang** [comment]
when key code between 96 and 105, it still switched to minute mode.

**Comment by loebi-ch** [comment]
I cannot reproduce... can you please post your ClockTimePicker options.

**Comment by wzshuang** [comment]
The bug exist at version  2.1.5, seems that it has been fixed at 2.1.6, nice job.

**Comment by wzshuang** [comment]
In your demo page, Time picker with precision with 60.

**Comment by loebi-ch** [comment]
Seems that 2.1.6 fixes this issue.
